### ISSUE TITLE
Create wallet session for Akshith and Toronto Legal Hackers as part of “The Great Blockchain Bake Off of 2016”

### ISSUE THREAD

**Issue by dazzaji** [CIVICS/GreatBlockchainBakeOffOf2016#1]
**Update:** Current idea is demo of CoinBase as "hybrid" solution for Blockchain and Payments

**Note:** The Smart Contract hybrid use case connected to "Loan" demonstrates something different - not focused on payment transaction rather focused on other legal terms and capabilities like evidence of a legal contract and trigger of a legal process such as repossession.  Trigger may be non-playment in a bank account and API from bank or web-hook representing an event ingestible by an Oracle to trigger for example notice of default on loan or repossession request.

Create wallet session for Akshith and Toronto Legal Hackers as part of “The Great Blockchain Bake Off of 2016” (3:10pm Agenda Item for TRANSACT Tech Boston: http://www.electran.org/conferences-events/2016-transact-tech-boston/) 
1. Demo Top New/Crypo & Old/Fiat Digital Wallets to Rate/Evaluate Them (the “Bake-Off”)
New: BitCoin and Ethereum Wallets (SuperSet of Wallets: https://bitcoin.org/en/choose-your-wallet)
https://github.com/ethereum/mist/releases
Managed: (BitCoin Wallets Managed by CoinBase or Other Exchanges)
Blockchain 
https://blockchain.info/wallet/
Not-Managed: (BitCoin Wallets Not Third-Party Managed Include)
Bread: https://breadwallet.com/ 
Multi-Sig Wallets: 
Old: Google, PayPal, Apple Pay, CU Wallet… other? 
See: http://www.cuwallet.com/ 
2. Opportunity to Demo a Hybrid Wallet Concept (Akshith)
https://www.coinbase.com/?locale=en 
- Show Crypto balances for bitcoin and/or ethereum and Fiat currency balances (ie in bank account and/or digital wallet if stored value, etc)
- Allow Conversion
- Demo some aspect of Payments
  - could be integration with Visa, Mastercard, etc (token-based standard… links to follow)
        - could be integration with ACH  bank to bank transfers (see link above)
        - could be integration with API for Svcs like Paypal, Square, etc  
        - (Please take a look at Circle and shout if you want to use and/or need any assist from them as they will be at and helping with the event on Sept 13th)
         - In a pinch, could be a GitHub app integration with 2 or more account eg: create file constituting an “invoice” in buyers GitHub repo and then (based on some event representing a payment confirmation) create file constituting a receipt in buyers repo.  

Notes:
- Look at open bazaar and exchange like coinbase
  https://support.coinbase.com/customer/portal/articles/1148716-payment-methods-for-us-customers 
  This is the punchline functionality for the ETA/Payments audience: 
  Deposit/Pay to fiat currency accounts including:
  bank transfers & bank wires 
  Paypal is great for demonstrating online merchants
  Feel free to also outreach to exchanges like ZebPay or CoinSecure (Indian Based) if you want to do something that is better with them.

For outreach to others as part of getting demo together, please just CC the rest of the Bake Off team:
Joanna Lehrer:
Amy ter Haar, 
Dazza Greenwood:
- If you get chance, please look at payswarm by http://digitalbazaar.com/
- Volatility is an issue if value stored in cyptocurrency and expended in fiat currency.  It would be ideas to demonstrate at least one use case that:
  Provides Evidentiary and Smart Contracts Capability via Blockchain
  Provides Depository (Stored Value) and Fiat Currency Receive/Pay Capability
  Including BitCoin and/or Ether is very good additional value and necessary to some extent to pay for any transaction on blockchain but can be de-linked from demo of a core-use case to existing payments industry who are looking for whether/how they can use Blockchain as part of consumer purchase from merchant in ordinary commerce and/or consumer transaction with their own or another person’s bank.

**Comment by akshithg** [comment]
Completed !
